keys:
  - &users:
    - &xhos age1s2u3cxpvurmvpq987a0hqv0ujs2zu587uelsjlpt9aeyqvgznsxqt3kyg3
  - &hosts:
    - &zireael age17lfeyqt968f6wgmzhs6amnll76wd3w56hdjemep9mh3w9qw2ud5qxr8q5s

creation_rules:
  - path_regex: ./secrets.yaml$
  - key_groups:
      - age:
          - *xhos
          - *zireael
