{
  imports = [
    ./aard.nix
    ./clipse.nix
    # ./discord.nix
    ./fastfetch.nix
    ./firefox
    ./hypr
    ./impermanence.nix
    ./mako.nix
    ./music
    ./obs.nix
    ./options.nix
    ./prompts
    ./rofi.nix
    ./secrets.nix
    ./shells
    ./stylix.nix
    ./telegram.nix
    ./terminals
    ./waybar
    ./web-apps
    ./whisper.nix
    ./zed.nix
    ./fonts
    ./xdg.nix
    ./dankshell.nix
  ];
}
