keys:
  - &dev age15dmxpcec55u7xw304v5q79fdmelp94ds673v3h9dm7c47z9weuhsc55sxy
  - &hosts:
    - &vyverne age1d8n9zkelkeyjgtqfhh8ngk8v2thkg42d4ulmk5r49cc9g9aqvd2qxt7eg7
    - &zireael age1e4g06wlq0ynlswv5qgqcr575pp3gw5hn0644hwa5cwgek4mygpnsxewads

creation_rules:
  - path_regex: ./secrets.yaml$
  - key_groups:
      - age:
          - *dev
          - *vyverne
          - *zireael
