keys:
  - &users:
    - &xhos age15nkvj70c0es6zf90p6hwc63qz82c8rrztype264ghnvl49zazexqnsxha3
  - &hosts:
    - &zireael age1jsuten5w75mds0h64jl9u695877khyhkef5wxnmvs6z55ct06v3sa3xgfn

creation_rules:
  - path_regex: ./secrets.yaml$
  - key_groups:
      - age:
          - *xhos
          - *zireael
