{
  imports = [
    ./ai.nix
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./gnome.nix
    ./ly.nix
    ./nvidia.nix
    ./obs.nix
    ./options.nix
    ./plasma.nix
    ./rclone.nix
    ./regreet.nix
    ./sddm.nix
    ./steam.nix
    ./tuigreet.nix
    ./virtualisation.nix
    ./wayland.nix
    ./xfce.nix
  ];
}
