{
  imports = [
    ./ai.nix
    ./bluetooth.nix
    ./cosmic.nix
    ./gnome.nix
    ./hyprland.nix
    ./nvidia.nix
    ./options.nix
    ./plasma.nix
    ./rclone.nix
    ./regreet.nix
    ./sound.nix
    ./steam.nix
    ./tuigreet.nix
    ./virtualisation.nix
    ./wayland.nix
    ./xfce.nix
  ];
}
