name: Build NixOS Installer ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build NixOS ISO
        working-directory: .
        run: |
          nix build .#nixosConfigurations.nyx.config.system.build.isoImage --no-link

      - name: Find ISO output
        id: find_iso
        run: |
          # locate the built ISO in the Nix store
          iso=$(find $(nix eval --raw .#nixosConfigurations.nyx.config.system.build.isoImage) \
                     -type f -name '*.iso' | head -n1)
          echo "found ISO at $iso"
          # new environment-files syntax:
          echo "path=$iso" >> $GITHUB_OUTPUT

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-installer-iso
          path: ${{ steps.find_iso.outputs.path }}
